language: node_js
node_js:
  - "stable"
cache: yarn
script:
  - yarn test
  - yarn build
deploy:
  provider: heroku
  api_key: heroku_api_key
  app:
    master: wunderbar-humber
    develop: wunderbar-humber-dev
notifications:
    slack: fishsticks-humber:yBlIrV8LokTLApwdkvVZJ8K9
    email: false
