language: node_js
node_js:
  - "stable"
cache: yarn
script:
  - yarn test
notifications:
  slack:
    rooms: 
      - secure: $slack_travis
    on_success: change
    on_failure: change
  email: false
